### PR TITLE
fix(backend): access to dashboard admin using token 

### LINKED ISSUE #26: Create a RolesGuard
Implement a RolesGuard that reads the user roles from the request (populated from the validated Auth0 token) and checks whether the user has the required role to access a given route. The guard should use metadata defined via the @Roles() decorator and return 403 Forbidden if the user lacks the necessary role. This guard will be used to protect /admin routes by enforcing that only users with the admin role can access them.

### Checklist
- [ ] Create a RolesGuard class that implements CanActivate
- [ ] Extract roles metadata using Reflector and the `ROLES_KEY`
- [ ] Read the user’s roles from request.user (injected by JwtStrategy)
- [ ] Compare required roles with the user’s roles
- [ ] Return true if the user has at least one required role; otherwise throw ForbiddenException
- [ ] Use `@Roles('admin')` decorator on protected /admin routes
- [ ] Apply it selectively with `@UseGuards()`
- [ ] Ensure routes without `@Roles()` metadata are not blocked by the guard
- [ ] Add test cases for:
  - [ ] User with correct role
  - [ ] User without required role
  - [ ] No roles present in JWT

### LINKED ISSUE #30: Create controller for /admin/profile

### PR DESCRIPTION
**Pull request by JMB-7**

### CODE REVIEW

File: backend/src/admin/admin.controller.ts [hunk 1]
```diff
@@ -1,11 +1,14 @@
...
 
 @Controller('admin')
+@UseGuards(JwtAuthGuard, RolesGuard)
 export class AdminController {
+  @Roles('read:admin_dashboard')
   @Get('dashboard')
-  @Roles('admin')
   getDashboard() {
-    return { message: 'Welcome to admin dashboard' };
+    return { message: 'Welcome to the3 admin dashboard' };
```
Comment (hndoss) [inline backend/src/admin/admin.controller.ts]: For the record, currently we are not planning to have a dashboard. It is fine for the first implementation just to validate the auth0 integration.

File: backend/src/admin/admin.controller.ts [hunk 2]
```diff
@@ -1,11 +1,14 @@
-import { Controller, Get } from '@nestjs/common';
+import { Controller, Get, UseGuards } from '@nestjs/common';
 import { Roles } from '../auth/roles.decorator';
+import { RolesGuard } from '../auth/roles.guard';
+import { JwtAuthGuard } from '../auth/jwt-auth.guard';
 
 @Controller('admin')
+@UseGuards(JwtAuthGuard, RolesGuard)
 export class AdminController {
+  @Roles('read:admin_dashboard')
```
Comment (hndoss) [inline backend/src/admin/admin.controller.ts:9]: We will need to define permissions assigned to the admin role. No action needed for now, but this permission might change in the near future.

File: backend/src/auth/jwt.strategy.ts [hunk 3]
```diff
@@ -6,29 +6,23 @@ import * as jwksRsa from 'jwks-rsa';
 
 @Injectable()
 export class JwtStrategy extends PassportStrategy(Strategy) {
-  constructor(private readonly configService: ConfigService) {
-    const domain = configService.get<string>('auth.domain');
-    const audience = configService.get<string>('auth.audience');
-    const issuer = configService.get<string>('auth.issuer');
-
+  constructor(configService: ConfigService) {
```
Comment (hndoss) [inline backend/src/auth/jwt.strategy.ts:9]: I think we should stick with the auth namespaced config pattern instead of inline access. For consistency and maintainability, let’s continue using keys like auth.issuer rather than configService.get('AUTH0_ISSUER').

File: backend/src/auth/jwt.strategy.ts [hunk 4]
```diff
@@ -6,29 +6,23 @@ import * as jwksRsa from 'jwks-rsa';
...
-      algorithms: ['RS256'],
     });
   }
 
   async validate(payload: any) {
-    return {
-      userId: payload.sub,
-      email: payload.email,
-    };
+    return { userId: payload.sub, ...payload };
```
Comment (hndoss) [inline backend/src/auth/jwt.strategy.ts]: It’s safer to explicitly declare what we want to expose in `req.user`. This aligns with the principle of least privilege, avoids unintentionally leaking claims, and makes the structure of req.user predictable and maintainable across the application.

File: backend/src/app.module.ts [hunk 5]
```diff
@@ -29,10 +24,9 @@ import authConfig from './config/auth.config';
       synchronize: true,
     }),
     EntitiesModule,
-    AuthModule,
```
Comment (hndoss) [inline backend/src/app.module.ts:32]: This is required to keep using auth namespaced config pattern.

File: backend/src/app.module.ts [hunk 6]
```diff
@@ -6,16 +6,11 @@ import { EntitiesModule } from './entities/entities.module';
...
-import { configValidationSchema } from './config/config.validation';
-import databaseConfig from './config/database.config';
-import authConfig from './config/auth.config';
 
 @Module({
   imports: [
     ConfigModule.forRoot({
       isGlobal: true,
-      load: [databaseConfig, authConfig],
-      validationSchema: configValidationSchema,
```
Comment (hndoss) [inline backend/src/app.module.ts:18]: Is there a reason to remove the utilization of the config files inside `./config/`?

File: backend/src/app.module.ts [hunk 7]
```diff
@@ -6,16 +6,11 @@ import { EntitiesModule } from './entities/entities.module';
 import { AppController } from './app.controller';
 import { AppService } from './app.service';
 import { AdminModule } from './admin/admin.module';
-import { configValidationSchema } from './config/config.validation';
```
Comment (hndoss) [inline backend/src/app.module.ts:9]: This is a requirement of #25:
> Application fails with a clear error if the config values are missing or invalid

File: backend/src/auth/auth.modules.ts [hunk 8]
```diff
@@ -1,17 +1,10 @@
 import { Module } from '@nestjs/common';
-import { JwtModule } from '@nestjs/jwt';
 import { PassportModule } from '@nestjs/passport';
 import { JwtStrategy } from './jwt.strategy';
-import { AuthService } from './auth.service';
+import { ConfigModule } from '@nestjs/config';
 
 @Module({
-  imports: [
```
Comment (hndoss) [inline backend/src/auth/auth.modules.ts:8]: We should keep using `AuthService` unless there is a reason to remove it.

File: backend/src/auth/roles.guard.ts [hunk 9]
```diff
@@ -1,22 +1,28 @@
...
 import { Reflector } from '@nestjs/core';
-import { ROLES_KEY } from './roles.decorator';
 
 @Injectable()
 export class RolesGuard implements CanActivate {
   constructor(private reflector: Reflector) {}
 
   canActivate(context: ExecutionContext): boolean {
-    const requiredRoles = this.reflector.getAllAndOverride<string[]>(ROLES_KEY, [
+    const requiredPermissions = this.reflector.getAllAndOverride<string[]>('roles', [
```
Comment (hndoss) [inline backend/src/auth/roles.guard.ts:9]: For the first iteration we just want to ensure that a user can access protected endpoints if the user is an admin. We are not covering the permissions yet.

**Comment by hndoss** [comment]
@JMB-7, I think this PR fits the needs of this task: #26.

File: backend/src/auth/roles.guard.ts [hunk 10]
```diff
@@ -1,22 +1,28 @@
...
+    const { user } = context.switchToHttp().getRequest();
+    const userPermissions = user?.roles || [];
+
+    const hasPermission = requiredPermissions.every((permission) =>
+      userPermissions.includes(permission),
+    );
 
-    if (!user || !requiredRoles.includes(user.role)) {
+    if (!hasPermission) {
       throw new ForbiddenException('Admin role required');
```
Comment (hndoss) [inline backend/src/auth/roles.guard.ts]: Since this is checking permissions, I think the message should be something like "Admin permissions required".

**Review by hndoss — CHANGES_REQUESTED** [review]
Looks really good! There are just two comments pending, and we also need to add tests.

Add test cases for:
- [ ] User with correct role
- [ ] User without required role
- [ ] No roles present in JWT

**Review by hndoss — APPROVED** [review]
